### ISSUE TITLE
requirements.txt not working

### ISSUE THREAD

**Issue by yunqili0809** [CASE-Lab-UMD/Router-Tuning-Mixture-of-Depths#1]
Could you give out a valid requirments.txt? The current version is your local path.

**Comment by Shwai-He** [comment]
Thank you for the reminder. I have uploaded the file.

**Comment by yunqili0809** [comment]
The current requirements.txt still has some problems on the conda part.
For the readme file, the script names were wrong.
For setup.py, we don't have the src and llmtune folder to get version
And the finetune_mindskip.py is missing import sys

**Comment by Shwai-He** [comment]
Thank you for pointing that out. I apologize for the inconvenience. I have updated both requirements.txt and finetune_mindskip.py. The setup.py file was redundant, so I have removed it.

**Comment by yunqili0809** [comment]
The current falsh-attn still requires setup.py
![image](https://github.com/user-attachments/assets/7b0e6b42-c9c8-4045-a0be-9e87544dc161)

**Comment by Shwai-He** [comment]
It seems an issue about flash-attn installation.
